baseurl: "" # The subpath of your site. Use "" if you're hosting a blog at the root level.
url: "https://rajivrnair.github.io" # the base hostname & protocol for your site.
title: "A Spoonful of Technology"


paginate: 3 #articles per page
paginate_path: /blog/page:num #makes pagination working


#contacts
git: "https://github.com/rajivrnair"  #Add your github url here.
stackoverflow: "http://stackoverflow.com/users/566434/rajiv" #Add your stackoverflow url here.
twitter: "https://twitter.com/gundsawada"  #Add your twitter url here.

#disqus comment
disqus:
    shortname: "rajivnair" #replace with your disqus comment short name

#google analytics
# google:
#     tracking-id: "" #paste your tracking id here
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

# This is used by feed.xml. Uncomment if you want to use it.
name: "A Spoonful of Technology"
description: "Where Rajiv R Nair blogs about technology"
author: "Rajiv R Nair"

exclude:
  - "README.md"
  - "CHANGELOG.md"
  - "Gemfile"
  - "Gemfile.lock"
permalink: :title
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
